name: Monitor Anddea Repo
on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering
jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Check Anddea Repo for Updates
        id: check
        run: |
          # Fetch the latest commit SHA from Anddea's repo
          LATEST_SHA=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/<anddea>/<revanced-patches>/commits?per_page=1 | jq -r '.[0].sha')
          # Check if the SHA has changed
          if [ ! -f "last_sha.txt" ] || [ "$(cat last_sha.txt)" != "$LATEST_SHA" ]; then
            echo "New update found! SHA: $LATEST_SHA"
            echo "NEW_UPDATE=true" >> $GITHUB_ENV
            echo "COMMIT_MESSAGE=$(curl -s -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/<AnddeaUsername>/<RepoName>/commits?per_page=1 | jq -r '.[0].commit.message')" >> $GITHUB_ENV
            echo "$LATEST_SHA" > last_sha.txt
          else
            echo "No new updates."
            echo "NEW_UPDATE=false" >> $GITHUB_ENV
          fi
      - name: Commit SHA File
        if: env.NEW_UPDATE == 'true'
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add last_sha.txt
          git commit -m "Update last SHA"
          git push
      - name: Send Telegram Notification
        if: env.NEW_UPDATE == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🔔 New update in Anddea/<RepoName>!
            Commit: ${{ env.COMMIT_MESSAGE }}
            Link: https://github.com/<AnddeaUsername>/<RepoName>
